### PR TITLE
Fix: Cursor.count was applying skip/limit by default

### PR DESCRIPTION
**Pull request by shaunburdick**
(Ok, it's late and I could be crazy at this point)
It seems Cursor.count was only returning the count with skip/limit applied.
According to the mongo docs: https://docs.mongodb.com/manual/reference/method/cursor.count/
I _believe_ it should return the count of all results unless you run `cursor.count(true)` (at least that's how the db seems to be working for me, I'm kinda new to Mongo)

This change was a little less straight forward but seems to work and all tests pass! It just feels a little less elegant so I'm open to achieving this a different way.

*NOTE*: This will totally break tests for people expecting the current (incorrect?) automatic application of skip/limit for count

### CODE REVIEW

**Comment by williamkapke** [comment]
Aahh... I _remember_ I didn't add `applySkipLimit` because `getDocs` caches the result in the `docs` variable. So, this will be incorrect if you call it **with**... and then **without** `applySkipLimit=true`.

like:
```js
var cursor = db.users.find().sort( { name: 1 } )
var count1 = cursor.count(true)
var count2 = cursor.count(false) // will return the cached `docs`
```

I don't remember if I had some extreme slowness that I was working around. 🤔 

Most likely the correct thing to do is to STOP caching the results and let it run every time. What do you think?

**Comment by shaunburdick** [comment]
Yeah, I see it now. Yeah, I want to say we can remove that caching. The only slowness would be if someone was doing a `while (cursor.hasNext() && doc = cursor.next()) {}` type stuff, but who does that?!

I will add a test and remove the cache to validate that it's working.

**Comment by shaunburdick** [comment]
Added `collection.count` from #13 as it seems that PR died and I was in here anyways.

**Comment by shaunburdick** [comment]
Seems to work well in my tests. I didn't see any performance issues testing handfuls of documents.
What do  you think?

**Comment by williamkapke** [comment]
Yup. I think it'll be ok. Published 2.3.0.

Thanks again 👍

**Pull request merged**
