### PR TITLE
Quick fix to support some mongo query operators and regexp on .find()

### PR DESCRIPTION
**Pull request by hlfshell**
This is a quick fix to add support for regexp, and operators such as $gte in mongo. This is an initial draft I needed to do for a project and thought I'd share to see if you thought this was a good direction.

Pull request does not need to be accepted, this can just be for review as well.

Features not extended to .findOne() yet.

### CODE REVIEW

**Comment by hlfshell** [comment]
This is embarrassing - I found a problem in this code already. Allow me to fix over the weekend before considering.

**Comment by hlfshell** [comment]
OK, fixed. I was checking the attribute type before the ! in the if statement.

This should work. Is it something you want me to expand upon? Maybe expand it to findOne (which uses .find instead of.where, and I don't know why?)

**Comment by williamkapke** [comment]
I really really like where this is going! It needs tests though. Any chance you can add some tests?

**Comment by hlfshell** [comment]
I'll try and expand it to find and findOne once I get back from holiday
travels.

On Sat, Dec 26, 2015 at 4:09 PM, William Kapke <notifications@github.com>
wrote:

> I really really like where this is going! It needs tests though. Any
> chance you can add some tests?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/williamkapke/mongo-mock/pull/3#issuecomment-167363676>
> .
>



-- 
~Keith

**Comment by williamkapke** [comment]
Actually, I just found https://www.npmjs.com/package/sift. I always wanted the query engine to be a standalone module anyhow. I'm going to try to integrate it and see what happens.

**Comment by hlfshell** [comment]
That's a far better way to do it. Let me know if you need help integrating it. For now I'll close the pull request.

**Comment by williamkapke** [comment]
Ok, it's done & published :)

**Comment by hlfshell** [comment]
Pulled out my changed mongo-mock for the new version in a project where I needed the $neq and $eq, and regex checks. All tests passed (that would have failed prior to my changes). Not the most extensive test but very promising. Great work!

**Pull request closed without merging**
