### PR TITLE
do not return empty arrays from findOne on brand new collection

### PR DESCRIPTION
**Pull request by Floby**

### CODE REVIEW

**Comment by williamkapke** [comment]
Good catch. Thanks for the PR!

**Comment by Floby** [comment]
no problem.
If you do not mind publishing it as a new patch version, I could remove a
workaround in my test.
thanks.

**Comment by williamkapke** [comment]
yup- I published 1.2.6. You're good to go.

**Comment by Floby** [comment]
thanks a lot!

**Pull request merged**
