### PR TITLE
add $push command for update action

### PR DESCRIPTION
**Pull request by fruch**

### CODE REVIEW

**Comment by williamkapke** [comment]
Nice! Thank you 😄

**Comment by fruch** [comment]
you're welcome, I was trying to also change to support setOnInsert together with this, but its a bit less trivial (change my code cause of that).

**Comment by fruch** [comment]
@williamkapke one more small favor, can you release a vesion with this ? (so I can move to formal version insted of my branch)

**Comment by williamkapke** [comment]
My error- I thought I did.

... I just published `mongo-mock@2.7.0`

**Comment by fruch** [comment]
@williamkapke million thanks !!! (that was quick)

**Pull request merged**
