### PR TITLE
Resolves #41 by adding Db.db function

### LINKED ISSUE #41: db: [Function: NotImplemented]
Is anybody working in this implementation?

I use it i my project because it constantly switch from a database to another, and is impossible to test.

Thanks in avance.

### PR DESCRIPTION
**Pull request by shaunburdick**

### CODE REVIEW

**Comment by williamkapke** [comment]
Yeah- this would work for a very basic start. Looking at the docs this looks quite a bit more complicated.

http://mongodb.github.io/node-mongodb-native/2.2/api/Db.html#db

Thoughts?

**Comment by williamkapke** [comment]
Also- any idea how this is done in v3 of the mongo api?

**Comment by shaunburdick** [comment]
Yeah, I went with a simple simple implementation at the moment.
The caching should be easy enough to do, I'll try to sneak it in at lunch.
The parent/child event emitter is probably easy too, just need to look up how to do that ;-)

**Comment by shaunburdick** [comment]
And it looks like db moves to the MongoClient in 3: https://mongodb.github.io/node-mongodb-native/3.0/api/MongoClient.html#db

**Comment by shaunburdick** [comment]
What version is this lib targeting?

**Comment by williamkapke** [comment]
It's gotten a long way with out defining that. Many of the "basic" things have been cross compatible- and some deprecated things have been left in... because having them made some people happy and didn't seem to hurt.

My tendency would be to go towards the latest & greatest... but I would hate to move to v3 and cut out someone that's stuck on v2!

What are your thoughts? Do you think it's possible to keep trying to support both?

**Comment by shaunburdick** [comment]
Yeah, I think the ambiguity has served it well so far. In this case I think we could add the `db` function in both places to keep that trend going

**Comment by radiovisual** [comment]
Just curious if this PR is going to be merged soon? Using this PR I am able to mock mongodb in jest with just two lines, which is a beautiful thing, but without this PR, I get the expected `Not Implemented PRs welcome!` message in my test failures.

**Comment by williamkapke** [comment]
Sorry for the Holiday delay. Merged- I'm ok with starting with this. Hopefully, if someone needs additional functionality we'll see another PR iterating on it :D

**Pull request merged**
