### PR TITLE
fix typo ObjectId -> ObjectID

### PR DESCRIPTION
**Pull request by kub1x**
Missed by one. Sorry for the extra PR.

### CODE REVIEW

**Comment by williamkapke** [comment]
How about having both? 😉 

See:
https://github.com/mongodb/node-mongodb-native/blob/a7fb4eaca3a03d0f6a823174fcf0baf5f5e530de/index.js#L39

**Comment by kub1x** [comment]
Ok. Both it is =)

**Comment by kub1x** [comment]
I rewrote the commit back then, so it's there to be merged ;)

**Comment by williamkapke** [comment]
Oh excellent- Thanks!

**Pull request merged**
